[package]
name = "boredphoton"
version = "0.1.0"
authors = ["SOFe <sofe2038@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.10.1"
crossbeam = "0.7.3"
log = "0.4.11"
pretty_env_logger = "0.4.0"
serde = {version = "1.0.114", features = ["derive"]}
serde_json = "1.0.56"
serenity = "0.8.6"
